### ISSUE TITLE
Istio Operator could not deploy an AWS Network Load Balancer with multiple SSL certifications. 

### ISSUE THREAD

**Issue by LYSingD** [istio/community#1184]
With Istio Operator, I cannot deploy an AWS Network Load Balancer with multiple SSL certifications. The ` service.beta.kubernetes.io/aws-load-balancer-ssl-cert` annotation can only assign one SSL certificate from ACM. However, it should be able to assign multiple SSL certificates as ref in the AWS Load Balancer Controller documentation: [link](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/guide/service/annotations.md)

Here is the `istio-installation-configs.yaml` I have:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: installed-state
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        k8s:
          service:
            externalTrafficPolicy: Local
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:xxxxxxxxxxxx:certificate/3e0ae8dd-d678-4cd0-97fd-d552ac264799, arn:aws:acm:us-east-1:xxxxxxxxxxxx:certificate/8de13d30-1c2a-4cc8-8cae-53cb58449fb0"
            service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-xxxxxxxxx,subnet-xxxxxxxxx,subnet-xxxxxxxxx"
```
Both certificates are from single region and generated by ACM. 

Here is the error message I got:
```
... error updating load balancer listener: "ValidationError: Certificate ARN 'arn:aws:acm:us-east-1:xxxxxxxxxxxx:certificate/3e0ae8dd-d678-4cd0-97fd-d552ac264799, arn:aws:acm:us-east-1:xxxxxxxxxxxx:certificate/8de13d30-1c2a-4cc8-8cae-53cb58449fb0' is not valid\n\tstatus code: 400
 ```

I appreciate your help in advanced! :)
