### ISSUE TITLE
"Copy JWT Claims to HTTP Headers" not work as expect when I have Chinese character in jwt

### ISSUE THREAD

**Issue by DreamParadise** [istio/community#1357]
Raw JWT Payload：
![image](https://github.com/istio/community/assets/3191003/283925b7-d67e-47fe-a489-8704291f2a5d)

request authentication:
```yml
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: jwt
  namespace: xxx
spec:
  jwtRules:
    - issuer: oxxx
      outputClaimToHeaders:
        - claim: empName
          header: x-claim-emp-name
  selector:
    matchLabels:
```

read from header in target pod
![image](https://github.com/istio/community/assets/3191003/3e174169-b14a-48d9-9b28-9e3cb1a9a626)
