### ISSUE TITLE
Local rate limits by path not working

### ISSUE THREAD

**Issue by Anonymous-Coward** [istio/community#1440]
This is reopening https://github.com/istio/istio/issues/49432 - that ticket was closed as being stale, but we did provide the required feedback in time, we just didn't get any answer from the istio developers.

We use this envoy filter to enable distinct local rate limits by path:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: local-rate-limit
  namespace: local-app
spec:
  workloadSelector:
    labels:
      label: some-label
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            stat_prefix: http_local_rate_limiter
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND
      routeConfiguration:
        vhost:
          name: inbound|http|80
          route:
            action: ANY
    patch:
      operation: MERGE
      value:
        route:
          rate_limits:
          - actions:
            - header_value_match:
                descriptor_key: path
                headers:
                - name: :path
        typed_per_filter_config:
          envoy.filters.http.local_ratelimit:
            '@type': type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            descriptors:
            - entries:
              - key: path
                value: /some/heavy/call
              token_bucket:
                fill_interval: 30s
                max_tokens: 2
                tokens_per_fill: 2
            - entries:
              - key: path
                value: /another/heavy/call
              token_bucket:
                fill_interval: 30s
                max_tokens: 6
                tokens_per_fill: 6
            enable_x_ratelimit_headers: DRAFT_VERSION_03
            filter_enabled:
              default_value:
                denominator: HUNDRED
                numerator: 100
              runtime_key: local_rate_limit_enabled
            filter_enforced:
              default_value:
                denominator: HUNDRED
                numerator: 100
              runtime_key: local_rate_limit_enforced
            response_headers_to_add:
            - append: false
              header:
                key: x-local-rate-limit
                value: "true"
            stat_prefix: http_local_rate_limiter
            token_bucket:
              fill_interval: 30s
              max_tokens: 10
              tokens_per_fill: 10
```

With it applied, we expect the following number of successful requests per 30s:
- /some/heavy/call - 2 requests per pod
- /another/heavy/call - 6 requests per pod
- any other path: 10 requests per pod

There's also a rate limit of 100 requests per 30s applied to the istio ingress gateway into the cluster (two istio ingress gateway pods each allowing 100 requests per minute amounts to 200 requests per 30s overall).

If I start hammering some path outside of the namespace where the local rate limits envoy filter is applied, I get the 200 requests per 30s I expect answered with `200 OK`, alongside several thousands answered with `429 Too many requests`. If I hammer some path other than the two configured with special limits in the namespace where the envoy filter is applied, I get 20 requests per 30s answered with `200 OK`, and again, several thousands answered with `429 Too many requests` (10 requests for each of the two pods answering them). If I hammer either of the two special paths, instead of getting the small number of requests configured for them answered with `200 OK`, I still get 20 requests per 30s answered with `200 OK`, as if no rate limits by path are applied.

The generic rate limit for the entire namespace specified in the envoy filter _is_ applied, which means the port settings and everything else is correct. Why are the per path rate limits not applied?

Istio was deployed using `istioctl`, not `helm`.

```
$ istioctl version
client version: 1.21.0
control plane version: 1.21.0
data plane version: 1.21.0 (17 proxies)

$ kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4

```
