### ISSUE TITLE
Istiod stuck in endless loop after update to 1.7.1 due malformed virtual service

### ISSUE THREAD

**Issue by arnecls** [istio/community#454]
We just upgraded our control plane from istio 1.5.4 to istio 1.7.1.
To do so, we replaced the operator via rendered manifests, and then deployed a modified istio operator profile.yaml as the istio 1.5 operator profile is to a certain degree incompatible to istio 1.7 operator profile.

After the istio 1.7. operator accepted the new profile, it started deploying new versions of the istiod deployment.
These deployments did not become ready though, and were spamming `controller "networking.istio.io/v1alpha3/VirtualService" is syncing...`.

Turned out this was due to a resource deployed by Google CloudRun custom domain mapping that was not matching the `networking.istio.io/v1beta1` but would have matched the `networking.istio.io/v1alpha3` API.

The resource in question.

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: crowd
  ownerReferences:
spec:
  gateways:
  - knative-serving/gke-system-gateway
  - knative-serving/knative-ingress-gateway
  - mesh
  hosts:
  - our.public.ingress.domain
  http:
  - appendHeaders:
      K-Original-Host: our.public.ingress.domain
    rewrite:
      authority: our.internal.ingress.domain
    route:
    - destination:
        host: cluster-local-gateway.gke-system.svc.cluster.local
        port:
          number: 80
      weight: 100
    websocketUpgrade: true
```

I don't know why `networking.istio.io/v1beta1` was used and not `networking.istio.io/v1alpha3`.
However, until this resource was deleted, the istiod pods did not recover.

So two questions here
1. Was the resource API version implicitly updated?
2. Should istiod not simply ignore this resource and continue?
