### ISSUE TITLE
Redirect a 403 better solution?

### ISSUE THREAD

**Issue by rparree** [istio/community#500]
Hi,

I need a custom 403 page and created the filter below. Is this the best way, is there an easier technique?

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: 403-redirect
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          name: "0.0.0.0_8443"
          filterChain:
            sni: "xxxxxxxxxxxxx"
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.router
      patch:
        operation:  INSERT_BEFORE
        value:
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inline_code: |
              function envoy_on_response(response_handle)
                local headers = response_handle:headers()
                if headers:get(":status") == "403" then
                   headers:add("Location", "/403.html");
                   headers:replace(":status","308")
                end
              end
```
Initially i wanted to use Envoy's `local_reply_config`, but it did not have any effect. 

Ideally i would've liked to send back a 403 with custom HTML from an endpoint available in the Envoy cluster.

tx.,
