### ISSUE TITLE
Metrics for galley and citadel 

### ISSUE THREAD

**Issue by mohan-nagandlla** [istio/community#710]
Hi all,

I have deployed the istio 1.13 version and I have enabled the Prometheus service monitor and pod monitor for istiod and envoy metrics. I am able to get the istio_agent metrics and pilot metrics and envoy metrics the thing is like I am just getting 3 metrics for the galley and citadel. how to get all the metrics and isn't istiod not cover all the components? 

i used this manifest file to add the scrap target to Prometheus do I need to add more 

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-stats-monitor
  namespace: istio-system
  labels:
    purpose: prometheus-prometheus
spec:
  selector:
    matchExpressions:
    - {key: istio-prometheus-ignore, operator: DoesNotExist}
  namespaceSelector:
    any: true
  jobLabel: envoy-stats
  podMetricsEndpoints:
  - path: /stats/prometheus
    interval: 15s
    relabelings:
    - action: keep
      sourceLabels: [__meta_kubernetes_pod_container_name]
      regex: "istio-proxy"
    - action: keep
      sourceLabels: [__meta_kubernetes_pod_annotationpresent_prometheus_io_scrape]
    - sourceLabels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      targetLabel: __address__
    - action: labeldrop
      regex: "__meta_kubernetes_pod_label_(.+)"
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    purpose: prometheus-prometheus
  name: istio
  namespace: istio-system
spec:
  endpoints:
  - path: /metrics
    port: http-monitoring
  - path: /stats/prometheus
    relabelings:
    - action: keep
      regex: .*-envoy-prom
      sourceLabels:
      - __meta_kubernetes_pod_container_port_name
  namespaceSelector:
    matchNames:
    - istio-system
  selector:
    matchLabels:
      release: istio
```

![image](https://user-images.githubusercontent.com/52690110/159231235-4635a5b5-6e10-4ee0-bc00-dee0a8313edb.png)
![image](https://user-images.githubusercontent.com/52690110/159231319-d892cdf1-bf4a-4f75-8796-50716a5b5a1e.png)
