### ISSUE TITLE
looking for guidance of a migration from Nginx ingress to Istio Ingress

### ISSUE THREAD

**Issue by xudesheng** [istio/community#718]
I have a cluster deployed on AKS and the helm chart is using Nginx-Ingress. Before I explore more benefits of Istio, I want to simply migrate the ingress to Istio first.
I'm following the guide in the [https://istio.io/latest/docs/setup/install/helm/](https://istio.io/latest/docs/setup/install/helm/). The next step for me is to migrate all of the annotations. The current annotations are:
```
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /Dummyapp
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
```

Is there a quick guide which is talking about a simple mapping of annotations between `Nginx` and `Istio`? 

Thanks.
